version: '3'

services:
  database:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./misc/:/docker-entrypoint-initdb.d
    platform: linux/x86_64 

  api:
    build: ./backend
    container_name: api_container
    ports:
      - 3001:3001
    depends_on:
      - database
    volumes:
      - ./backend:/app-back

  web:
    build: ./frontend/caminheiros
    container_name: web_container
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./frontend/caminheiros:/app-front
