version: '3'

services:
  database:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "America/Sao_Paulo"
    volumes:
      - ./misc/:/docker-entrypoint-initdb.d
